### ISSUE TITLE
PHP Fatal Error when choosing CMIS driver

### ISSUE THREAD

**Issue by jdequeant** [dkd/typo3-ext-cmis-service#1]
Hi,

I've got a PHP Fatal error when I choose CMIS Driver in new File Storage :
"PHP Fatal error: Class 'Dkd\\PhpCmis\\Enum\\BindingType' not found in .../typo3conf/ext/typo3-ext-cmis-service/Classes/Configuration/Definitions/MasterConfiguration.php on line 55"

Effectively, in this file :
\typo3-ext-cmis-service\Classes\Configuration\Definitions\CmisConfiguration.php
there is "use Dkd\PhpCmis\Enum\BindingType;" on line 4.

When I search this namespace in the extension, I realize that its doesn't exists.

Can you give me a patch for this issue ?

Cheers,

Johan DEQUEANT.
W-seils, Nantes.

**Comment by sascha-egerer** [comment]
Hello,

the mentioned file is part of the cmis-client library and the file does exist. https://github.com/dkd/php-cmis-client/blob/master/src/Enum/BindingType.php

How have you installed the extension? The extension currently requires that you install it in composer mode and use the composer autoloader so all namespaces of third party packages are registered correctly.

**Comment by jdequeant** [comment]
OK thanks,
Effectively I've install it without composer I've just cloned the git repo, I retry...

**Comment by p380** [comment]
Hy,

Are there any instructions on how to install it?

**Comment by sascha-egerer** [comment]
@p380 `composer require dkd/cmis-service`

**Comment by p380** [comment]
first download the module in folder typo3conf/ext via the git clone command?

**Comment by sascha-egerer** [comment]
@p380 You have to install TYPO3 via composer to use this extension and then install the extension via composer 
Install TYPO3
https://docs.typo3.org/typo3cms/InstallationGuide/QuickInstall/Composer/Index.html
Install extensions:
https://docs.typo3.org/typo3cms/InstallationGuide/ExtensionInstallation/Index.html#install-an-extension-with-composer

**Comment by p380** [comment]
I successfully installed typo3 through the composer

if I run the following command, I get an error. In which folder do I run it (typo3conf / ext) or can I load (save) the composer.json file from the module?

composer require dkd / cmis-service

error:
                                                                                                                                                                                                
  [InvalidArgumentException]                                                                                                                                                                    
  Could not find a matching version of package dkd/cmis-service. Check the package spelling, your version constraint and that the package is available in a stability which matches your minim  
  um-stability (stable).   

thanx

**Comment by sascha-egerer** [comment]
@p380 Please try again with `composer require dkd/cmis-service:dev-master`.
And please note that this extension is currently not maintained and may not work anymore with current TYPO3 versions. If you need further (payed) support feel free to contact me.
